plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.0'
}

group = 'io.github.maninmyvan'
version = '1.0.7'

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.0.0'
    compileOnly 'org.spigotmc:spigot-api:1.17.1-R0.1-SNAPSHOT'
    implementation 'org.bstats:bstats-bukkit:3.0.2'
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
}

tasks.shadowJar {
    dependsOn(tasks.jar)
    archiveClassifier = ""
    relocate("org.bstats", "io.github.maninmyvan.dyeableshulkers.bstats")
}

tasks.assemble {
    dependsOn(tasks.shadowJar)
}

java.sourceCompatibility = JavaVersion.VERSION_1_8
java.targetCompatibility = JavaVersion.VERSION_1_8
