name: DyeableShulkers
main: io.github.maninmyvan.dyeableshulkers.DyeableShulkers
version: 1.0.3
api-version: 1.13
description: makes shulkers dyeable
permissions:
  dyeableshulkers.dye:
    default: true
    description: Whether the player can dye shulkers
    children:
      dyeableshulkers.dye.swing:
        default: true
        description: Whether the player will swing their hand when dyeing shulkers
      dyeableshulkers.dye.sound:
        default: true
        description: Whether a sound should play when the player dyes a shulker
