name: DyeableShulkers
main: io.github.maninmyvan.dyeableshulkers.DyeableShulkers
version: 1.0.0
api-version: 1.13
permissions:
  dyeableshulkers.dye:
    default: true
    description: Whether the player can dye shulkers
